### ISSUE TITLE
NameError: name 'tw' is not defined | Tweets Cog

### ISSUE THREAD

**Issue by Instantducks** [TrustyJAID/Trusty-cogs-archive#20]
![image](https://user-images.githubusercontent.com/1596590/43234872-357060f4-9044-11e8-863c-ec6bb91bc519.png)

**Comment by TrustyJAID** [comment]
You need to install tweepy for the cog to work.

**Comment by Instantducks** [comment]
May have realized that about 30 seconds after opening Thanks!54
