### ISSUE TITLE
Chatterbot cog error

### ISSUE THREAD

**Issue by DevilXD** [TrustyJAID/Trusty-cogs-archive#7]
Error: https://i.imgur.com/AWZZEEF.png

I also had problems installing pip and chatterbox module through pip, so I did it manually with the `--user` flag. This seems unsolvable =/

I really wanted to try out this cog...

**Comment by TrustyJAID** [comment]
The cog can be fun for a short while, It tracks conversations across all the bots servers and channels if the bot can see the conversations then uses those to pull for responses although it's quite buggy. I had it running for several months until the database got so large that it would freeze the bot until a response was found sometimes taking up to 45 seconds. It was not an ideal way to build a chat interface. I recommend using the cleverbot cogs for redbot in the meantime as this one still requires a lot of work.

To solve your issue though ensure that mongoDB is installed on your computer and that a database is created without a password for it to connect to then ensure that the service is running for MongoDB.

**Comment by Jatts-Art** [comment]
Yup go use Cleverbot instead and spend money on something that should be free, nice solution!

**Comment by DevilXD** [comment]
@RecklessJames The point was that this cog allows starting learning from scratch, adjusting to the servers the bot is in, so keeping the theme etc. Much better than Cleverbot given enough input and learning period.
Closing because I already gave up on solving this.
